// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'D:/javaComment/v5/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import NotificationOutlined from 'D:/javaComment/v5/node_modules/@ant-design/icons/es/icons/NotificationOutlined';
import ProfileOutlined from 'D:/javaComment/v5/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import MenuOutlined from 'D:/javaComment/v5/node_modules/@ant-design/icons/es/icons/MenuOutlined';
import NodeIndexOutlined from 'D:/javaComment/v5/node_modules/@ant-design/icons/es/icons/NodeIndexOutlined';
import UsergroupDeleteOutlined from 'D:/javaComment/v5/node_modules/@ant-design/icons/es/icons/UsergroupDeleteOutlined';
import IdcardOutlined from 'D:/javaComment/v5/node_modules/@ant-design/icons/es/icons/IdcardOutlined';
export default { HomeOutlined, NotificationOutlined, ProfileOutlined, MenuOutlined, NodeIndexOutlined, UsergroupDeleteOutlined, IdcardOutlined };
