// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'F:/apiPublic/frontend/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import ApiOutlined from 'F:/apiPublic/frontend/node_modules/@ant-design/icons/es/icons/ApiOutlined';
export default { HomeOutlined, ApiOutlined };
