// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import ApiOutlined from 'F:/apiPublic/frontend/node_modules/@ant-design/icons/es/icons/ApiOutlined';
export default { ApiOutlined };
